server:
  port: 9090

spring:
  application:
    name: GrowTechStack

  datasource:
    url: jdbc:h2:file:./GrowTechStack.db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      continue-on-error: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: alpha

logging:
  level:
    org.hibernate.orm.queries: info
    com.gts.collector: debug
