server:
  port: 29999

spring:
  application:
    name: gts-collector-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: devfeed-summary-result
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.gts.collector.global.kafka.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.gts.collector.global.kafka.dto.SummaryResultMessage"

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: alpha

ai-summary:
  base-url: ${AI_SUMMARY_BASE_URL:http://localhost:29998}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
